### ISSUE TITLE
JSON files don't have to be exactly or very close to 10MB.

### ISSUE THREAD

**Issue by exube** [neha45556/geolocatedTweets#1]
We don't need to check the filesize every time.  A tweet is typically about 28 characters long.  Along with data padding and URL stuffs, on average, we can assume each tweet takes about 150-250 bytes. 

This generally means we can keep a list of tweets in memory, and periodically dump this list to disk, only starting a new file (and list) when we have about 50k items in memory.  (Definitely better than using `stat` every time we receive a tweet, anyways...)

**Comment by exube** [comment]
I'm currently working on dumping these tweets to JSON files.

**Comment by exube** [comment]
Correction: each tweet actually takes around 150 bytes without a link, and 200-250 bytes with a link.  On average, this means about 50k tweets before starting a new file.

**Comment by neha45556** [comment]
I was doing it that way before because the assignment said to have up till
10mb of data in a file. And we only need the tweet in the file not the
extra stuff right unless its a url

**Comment by exube** [comment]
The assignment says "about 10MB" per file.  It doesn't have to be exact, and we'll probably take a much larger performance hit by `stat`ing the data file every time we have to write to it.  

As for the second point, it's easier to parse data when the entire file is in the same format, rather than havingt a few lines of raw tweet data, and a few other lines of JSON.  That way, we don't have to worry about parsing the data manually; we can just load it using a JSON library.

**Comment by neha45556** [comment]
I added you as contributor so you can put your code
